# Generated by Django 3.0.8 on 2020-07-31 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created',
            new_name='creada',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='complete',
            new_name='realizada',
        ),
    ]
